export { default as MainPage } from './MainPage'
export { default as NotFound } from './NotFound'
export { default as DetailPage } from './DetailPage'
export { default as CreatePage } from './QuestionCreate'
export { default as QuestionEditPage } from './QuestionEditPage'
